// @edu:student-assignment

package uq.comp3506.a1.structures;

/**
 * An interface representing a source or generator of elements of type {@code T}.
 *
 * @param <T> The type of elements generated by this oracle.
 */
public interface Oracle<T> {

    /**
     * Generates and returns the next random element.
     *
     * @return A generated element of type {@code T}.
     */
    public T nextT();

}
